version: "3.9"
services:
  # Application fedagmusic
  fedagmusic:
    container_name: fm-app
    build: ./
    image: fedagmusic:latest
    restart: always
    environment:
      spring_r2dbc_url: r2dbc:postgresql://postgres-bd:5432/fm-postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres

  #  PostgreSQL
  postgres:
    container_name: postgres-bd
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "fm-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    ports:
      - "5432:5432"
  #  PostgreSQL
  #При запуске этого скрипта рядом с ним создастся директория pgdata,
  # где будут располагаться файлы БД.
